### ISSUE TITLE
Add option to clear the song's queue

### ISSUE THREAD

**Issue by babski123** [babski123/Jettson-s-Karaoke#4]
Add an option to delete all the songs in the current user's queue

**Action plan**

- [x] add a new method in the 'Select' controller named 'clear'
- [x] The 'clear' method will delete all the songs in the current user's reserved songs and returns an API Trait response
- [x] Make a UI of it in select_song.php view
